# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 13:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='device',
            fields=[
                ('device_uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='devicelog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('moisture', models.FloatField()),
                ('waterpump', models.SmallIntegerField()),
                ('fan', models.SmallIntegerField()),
                ('heater', models.SmallIntegerField()),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='smartpanel.device')),
            ],
        ),
    ]
