# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartpanel', '0002_auto_20170510_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelog',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartpanel.device'),
        ),
    ]
